version: "2"
sql:
  - schema: "../../../migrations/"
    queries: "query/"
    engine: "postgresql"
    gen:
      go:
        package: "repo"
        out: "../../repo"
        emit_json_tags: true
        emit_db_tags:
        emit_empty_slices: true

#  - schema: "../../../migrations/000002_create_entries_table.up.sql"
#    queries: "query/entries.sql"
#    engine: "postgresql"
#    gen:
#      go:
#        package: "entry"
#        out: "../../entry"
#        emit_json_tags: true
#        emit_db_tags: true
#
#  - schema: "../../../migrations/000003_create_transfers_table.up.sql"
#    queries: "query/transfers.sql"
#    engine: "postgresql"
#    gen:
#      go:
#        package: "transfer"
#        out: "../../transfer"
#        emit_json_tags: true
#        emit_db_tags: true