// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package entry

import (
	"time"
)

type Entry struct {
	ID        int64 `db:"id" json:"id"`
	AccountID int64 `db:"account_id" json:"account_id"`
	// can be negative or positive
	Amount    int64     `db:"amount" json:"amount"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}
