// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package transfer

import (
	"time"
)

type Transfer struct {
	ID            int64     `db:"id" json:"id"`
	FromAccountID int64     `db:"from_account_id" json:"from_account_id"`
	ToAccountID   int64     `db:"to_account_id" json:"to_account_id"`
	Amount        int64     `db:"amount" json:"amount"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
}
